#ifndef ROBOTMAP_H
#define ROBOTMAP_H


//AUTONOMOUS
#define COMPETITION_LEFT_ENCODER_DIST_PER_FOOT 1306.46
//#define COMPETITION_RIGHT_ENCODER_DIST_PER_FOOT 1212.1212 //fake number
#define PRACTICE_LEFT_ENCODER_DIST_PER_FOOT 1306.46
//#define PRACTICE_LEFT_ENCODER_DIST_PER_FOOT 1150.0
//#define PRACTICE_RIGHT_ENCODER_DIST_PER_FOOT 1111.11 //fake

#define PRACTICE_LEFT_MOTOR_SPEED 0.87
#define PRACTICE_RIGHT_MOTOR_SPEED 0.8

#define COMPETITION_LEFT_MOTOR_SPEED 0.9	// 0.7 = 1 BALL            0.9 = 2 BALL
#define COMPETITION_RIGHT_MOTOR_SPEED 0.9 	// CHANGE TO 0.7 FOR 1 BALL AUTO


//MOTOR
#define LEFT_DRIVE_MOTOR 2
#define RIGHT_DRIVE_MOTOR 3

#define WINCH_MOTOR 1 //PWM
#define INTAKE_MOTOR 4 // PWM

//RELAY
#define COMPRESSOR_RELAY_CHANNEL 1


//SOLENOIDS
#define RAISE_INTAKE_ARM 7
#define LOWER_INTAKE_ARM 8
#define ENGAGE_SHOOTER_LATCH 5
#define RELEASE_SHOOTER_LATCH 6
#define ENGAGE_SHOOTER_BRAKE 2
#define RELEASE_SHOOTER_BRAKE 1

#define BRONCOBOTS_SOLENOID 2
#define BRONCOBOTS_PIN 2

#define CAMERALED_SOLENOID 2
#define CAMERALED_PIN 1

#define SHIFT_HIGH 3
#define SHIFT_LOW 4


//ANALOG
#define GYRO 2
#define PRESSURE_SWITCH 3

//DIGITAL INPUT
#define PRESSURE_SWITCH_CHANNEL 1

//DIGITAL OUTPUT
#define LEDLIGHTS_ALLIANCE_PIN 10
#define LEDLIGHTS_PATTERN_PIN_1 11
#define LEDLIGHTS_PATTERN_PIN_2 12

//SENSORS
#define BRAKE_SENSOR 7 //TTP
#define BALL_SENSOR 8
#define BAR_SENSOR 6
#define BOT_SENSOR 14

#define SHOOTER_POSITION_SENSOR 1


//ENCODERS
#define LEFT_ENCODER_CHANNEL_A 2
#define LEFT_ENCODER_CHANNEL_B 3
#define RIGHT_ENCODER_CHANNEL_A 4 
#define RIGHT_ENCODER_CHANNEL_B 5



//CONSTANT NUMBERS
#define PRACTICE_SHOOTER_POSITION_PRIMED_GOAL 324
#define PRACTICE_SHOOTER_POSITION_PRIMED_TRUSS 403
#define PRACTICE_SHOOTER_POSITION_UNPRIMED 661
#define SHOOTER_POSITION_TOLERANCE 20

#define WINCH_FORWARD_MOTOR_SPEED 1
#define WINCH_BACK_MOTOR_SPEED 0.8
#define INTAKE_MOTOR_SPEED 1

#define COMPETITION_SHOOTER_POSITION_PRIMED_GOAL 140
#define COMPETITION_SHOOTER_POSITION_PRIMED_TRUSS 180
#define COMPETIION_SHOOTER_POSITION_UNPRIMED 330

//BUTTONS - Stick 1

#define END_OF_MATCH_BUTTON 2

#define COLLECTOR_BUTTON 8 //before open house - 1
#define PASS_BALL_BUTTON 10 //before open house - 2

#define SHIFT_DOWN_BUTTON 11
#define SHIFT_UP_BUTTON 5

#define RAISE_INTAKE_BUTTON 5
#define LOWER_INTAKE_BUTTON 6

#define PRIME_COMPOSITE_BUTTON 7
#define PRIME_TRUSS_BUTTON 9
#define RELATCH_SHOOTER_BUTTON 1
#define PRIME_GOAL_BUTTON 3

#define FIRE_SHOOTER_BUTTON 12 //before open house - 10

#define LOWER_COLLECTOR_BUTTON 4

//BUTTONS - Stick 2

#define PIT_CONFIG_BUTTON 1
#define STOP_INTAKE_BUTTON 2
#define ENGAGE_BRAKE_BUTTON 3
#define RELEASE_BRAKE_BUTTON 4
#define FORWARD_INTAKE_BUTTON 5 
#define REVERSE_INTAKE_BUTTON 6
#define FORWARD_WINCH_BUTTON 7
#define BACK_WINCH_BUTTON 8
	
#define ENGAGE_LATCH_BUTTON 9
#define RELEASE_LATCH_BUTTON 10

#define STOP_WINCH_BUTTON 12


////////////////////////////////

#define SHOOTER_LATCH_ENGAGE 9
#define SHOOTER_LATCH_RELEASE 10


//XBOX CONTROLLER - 3

#define XBOX_A 1
#define XBOX_B 2
#define XBOX_X 3
#define XBOX_RIGHT_BUMPER 6
#define XBOX_LEFT_STICK_CLICK 9
#define XBOX_LEFT_BUMPER 5
#define XBOX_Y 4

#endif
